### ISSUE TITLE
Consider to make this repository as template repository

### ISSUE THREAD

**Issue by mramadhanrh** [photonstorm/phaser3-project-template#26]
Hi, as i know doing `npm install phaser3-project-template` in some empty directory is just making this repository to placed at `node_modules/` directory, while i think this could be solved by making this repository to a template repository.

here's the reference https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository.

by doing this we could create a phaser3 project based this repository.

Thanks in advance. 👍

**Comment by MADPT** [comment]
I was following the [Getting Started with Phaser 3](https://phaser.io/phaser3/gettingstarted) when following the "Webpack Project Template" instructions, the folder only contains `node_modules` and `package-lock.json`.  Due to the lack of the `package.json`, one can't run any of the [Available Commands](https://github.com/photonstorm/phaser3-project-template#available-commands).

This should be an easy fix, are you planning to do it soon @photonstorm? Thanks

**Comment by mramadhanr** [comment]
@photonstorm

**Comment by photonstorm** [comment]
This has been done.
